- name: WSL Configuration Playbook
  hosts: all
  become: true
  tasks:
    - name: Configure systemd with WSL-specific patches
      block:
        - name: Check the current default systemd target
          register: current_target
          changed_when: false
          ansible.builtin.command:
            cmd: systemctl get-default # noqa: command-instead-of-module

        - name: Set systemd default target to multi-user.target
          when: current_target.stdout != "multi-user.target"
          ansible.builtin.command:
            cmd: systemctl set-default multi-user.target # noqa: no-changed-when

        - name: Create WSL Keepalive Service
          notify:
            - reload systemd
          ansible.builtin.copy:
            src: wsl-keepalive.service
            dest: /etc/systemd/system/
            owner: root
            group: root
            mode: '0644'

        - name: Fix Systemd user-runtime service
          notify:
            - reload systemd
          ansible.builtin.copy:
            dest: /etc/systemd/system/user-runtime-dir@.service.d/override.conf
            content: |
              [Service]
              ExecStartPost=chown -R %i:%i /run/user/%i
            owner: root
            group: root
            mode: '0644'

        - name: Enable and start WSL Keepalive Service
          ansible.builtin.systemd:
            name: wsl-keepalive.service
            enabled: 'yes'
            state: started
            masked: 'no'

        - name: Disable WSL-incompatible services
          ansible.builtin.systemd:
            name: '{{ item }}.service'
            enabled: 'no'
            state: stopped
            masked: 'yes'
          loop:
            - systemd-networkd-wait-online
            - systemd-remount-fs

        - name: Enable systemd in the WSL config file (/etc/wsl.conf)
          community.general.ini_file:
            path: /etc/wsl.conf
            section: boot
            option: systemd
            value: 'true'
            backup: true
            mode: '0644'

    - name: Install and configure Docker
      block:
        - name: Install Docker
          ansible.builtin.apt:
            name:
              - docker
              - docker-compose
              - docker-buildx
            state: present
            update_cache: false

        - name: Enable Docker
          ansible.builtin.systemd_service:
            name: docker
            state: started
            enabled: true
            masked: 'no'

    - name: Install and configure sshd
      block:
        - name: Install SSH packages
          ansible.builtin.apt:
            name:
              - openssh-server
              - openssh-client
            state: present
            update_cache: false

        - name: Install common SSH host keys
          block:
            - name: Install public host keys
              ansible.builtin.copy:
                force: false
                src: 'ssh_keys/{{ item }}.pub'
                dest: /etc/ssh/
                mode: '0644'
              loop:
                - ssh_host_dsa_key
                - ssh_host_ecdsa_key
                - ssh_host_ed25519_key
                - ssh_host_rsa_key

            - name: Install private host keys
              ansible.builtin.copy:
                force: false
                src: 'ssh_keys/{{ item }}'
                dest: /etc/ssh/
                mode: '0600'
              loop:
                - ssh_host_dsa_key
                - ssh_host_ecdsa_key
                - ssh_host_ed25519_key
                - ssh_host_rsa_key

        - name: Enable sshd
          ansible.builtin.systemd_service:
            name: ssh
            state: started
            enabled: true
            masked: 'no'

        - name: Ensure PasswordAuthentication is set to yes
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^#?PasswordAuthentication'
            line: PasswordAuthentication yes
            validate: /usr/sbin/sshd -t -f %s
          notify:
            - restart ssh

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Restart ssh
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: ssh
